# Permalinks
permalink:          /:title/
paginate_path:      /:num/

# Setup
title:              adiaz.uy
description:        Personal site and web development blog of @HiroAgustin.
tagline:            HiroAgustin
url:                https://adiaz.uy
paginate:           20

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         ../_sass
  style:            :compressed

# About/contact
author:
  name:             Agustín Díaz
  url:              https://adiaz.uy
  email:            me@adiaz.uy
  twitter:          HiroAgustin
  picture:
                    path: https://adiaz.uy/public/Avatar.jpg
                    height: 300px
                    width: 300px

twitter:
  username:         HiroAgustin

social:
  links:
    - https://twitter.com/HiroAgustin/
    - https://github.com/HiroAgustin/
    - https://codepen.io/HiroAgustin/
    - https://linkedin.com/in/HiroAgustin/en/

# Defaults
defaults:
  - scope:
      path: ''
    values:
      image:
                    path: https://adiaz.uy/public/Logo.jpg
                    height: 300px
                    width: 300px

# Custom vars
version:            2.0.0
github:
  repo:             https://github.com/HiroAgustin/adiaz.github.com/
analytics_id:       UA-46154238-1

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Disable Rouge
kramdown:
  syntax_highlighter_opts:
    disable:        true

# Compress
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
