# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: adiaz.github.com
description: My personal site and blog
author:
  name: HiroAgustin
  email: hiroagustin@gmail.com

# Grunt handles images and assets.
exclude: ['images', 'styles', 'scripts', 'fonts', 'bower_components',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

url: http://adiaz.uy

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: null

# Output
permalink: /:title/
